### PR TITLE
params.sh proper check

### PR DESCRIPTION
**Pull request by Lex-2008**

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom make a build for @aleksandrychev to test, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4318/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4318/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4318/

**Comment by Lex-2008** [comment]
@aleksandrychev : do you want to test this manually before it got merged?

**Comment by Lex-2008** [comment]
tested with manually removing `/opt/cfengine/dc-scripts/params.sh` file - it works! Merging.

**Pull request merged**
