### PR TITLE
Dependency updates for master

### PR DESCRIPTION
**Pull request by Lex-2008**
Update openssl from 1.1.1c to 1.1.1d
Update libcurl-hub from 7.65.3 to 7.66.0
Update postgresql from 12beta3 to 12.0
Update php from 7.3.8 to 7.3.10
Update libcurl from 7.65.3 to 7.66.0

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom send to Jenkins for approval

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2936/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2936/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2936/

**Comment by vpodzime** [comment]
@cf-bottom jenkins again, please. Now that the OpenSSL failure on mingw seems to be resolved.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2970/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2970/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2970/

**Comment by vpodzime** [comment]
Looks OK, let's try with exotics:
[Build Status](https://ci.cfengine.com/job/pr-pipeline/2973/)

**Comment by vpodzime** [comment]
With *curl* builds on exotics fixed:
[Build Status](https://ci.cfengine.com/job/pr-pipeline/2985/) :crossed_fingers:

**Comment by vpodzime** [comment]
Build on exotics:
[Build Status](https://ci.cfengine.com/job/testing-pr/4740/)

**Pull request merged**
