### PR TITLE
Combined nick fixes

### PR DESCRIPTION
**Pull request by kacf**
From #130, #131 and #132, to save build time.

### CODE REVIEW

**Comment by kacf** [comment]
@nickanderson: I figured they were small enough to test together, and you don't have to wait as long!

**Comment by kacf** [comment]
trigger build

**Comment by nickanderson** [comment]
OK by me. I was only separating them because of check-list I am using.

**Comment by kacf** [comment]
Oh yes, I didn't mean to change that, this is merely a build convenience.

**Comment by kacf** [comment]
Package is done, did you want to test it first?

**Comment by nickanderson** [comment]
It worked OK for me.

**Comment by kacf** [comment]
Alright, they all looked like good fixes.

**Comment by nickanderson** [comment]
Did you pull those changes back into 3.9 and 3.7 ?

**Comment by kacf** [comment]
Done now!

**Pull request closed without merging**
