### PR TITLE
Upgrade dependencies for 3.8.1.

### PR DESCRIPTION
**Pull request by kacf**

### CODE REVIEW

**Comment by kacf** [comment]
trigger build

**Comment by kacf** [comment]
trigger build

**Comment by kacf** [comment]
trigger build

**Comment by kacf** [comment]
trigger build

**Comment by kacf** [comment]
trigger build

**Comment by kacf** [comment]
trigger build

**Comment by jimis** [comment]
Did we just get rid of a bunch of LMDB patches? Good stuff!

**Comment by kacf** [comment]
> Did we just get rid of a bunch of LMDB patches? Good stuff!

We did! :-)

**Comment by jimis** [comment]
Great! Are we still carrying any significant differences from upstream?

**Comment by kacf** [comment]
Not that much anymore. The four patches that remain add:

* Specific CFEngine tools (lmdump, etc.)
* Swaps barebone Makefile with autotools (this was needed for some of exotics)
* One performance optimization for HP-UX. This one was suggested by Howard himself, but I think he considers the platform too old to apply it upstream.

**Pull request merged**
