### PR TITLE
Dependency updates for 3.15.x

### PR DESCRIPTION
**Pull request by Lex-2008**
Update pcre from 8.43 to 8.44
Update openldap from 2.4.48 to 2.4.49
Update libcurl-hub from 7.67.0 to 7.69.0
Update git from 2.24.0 to 2.25.1
Update postgresql from 12.1 to 12.2
Update php from 7.4.0 to 7.4.3
Update libcurl from 7.67.0 to 7.69.0

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom now build it please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4795/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4795/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4795/

**Comment by Lex-2008** [comment]
@cf-bottom did you build exotics?

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4802/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4802/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4802/

**Pull request merged**
