### PR TITLE
Pcre sourceforge upgrade

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
@Lex-2008 testing this on ubuntu 20 buildslave with starter_pack and it seems to work well.

@cf-bottom jenkins with exotics please, thanks.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7282/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7282/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7282/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7299/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7299/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7299/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins again thanks, I had the wrong sourceforge url :p

**Review by Lex-2008 — APPROVED** [review]

**Comment by craigcomstock** [comment]
typo, try again @cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7303/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7303/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7303/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7304/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7304/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7304/

**Review by aleksandrychev — APPROVED** [review]

**Comment by craigcomstock** [comment]
Suse isn't happy with this change, but I will log a ticket for that.

https://tracker.mender.io/browse/ENT-7954

**Pull request merged**
