### PR TITLE
Dependency updates for 3.15.x

### PR DESCRIPTION
**Pull request by Lex-2008**
Update lcov from 1.14 to 1.15
Update openssl from 1.1.1k to 1.1.1l
Update openldap from 2.4.58 to 2.6.0
Update git from 2.31.1 to 2.33.1
Update postgresql from 12.7 to 12.8
Update php from 7.4.19 to 7.4.25
Update pcre from 8.44 to 8.45
Update libcurl-hub from 7.75.0 to 7.79.1
Update libcurl from 7.75.0 to 7.79.1
Update apache from 2.4.47 to 2.4.51

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom build exotics please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7283/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7283/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7283/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7288/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7288/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7288/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7291/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7291/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7291/

**Pull request merged**
