### PR TITLE
Use /var/cfengine/include in libattr/debian

### PR DESCRIPTION
**Pull request by olehermanse**
@kacf Submitting the changes you asked me to.

### CODE REVIEW

**Comment by olehermanse** [comment]
@kacf Done :)

**Comment by olehermanse** [comment]
https://ci.cfengine.com/job/bootstrap-enterprise-pr/109/
https://ci.cfengine.com/job/testing-enterprise-pr/95/

**Comment by olehermanse** [comment]
DO NOT MERGE. Red on all platforms, this change works for my local vm but not for the jenkins machines.

**Comment by kacf** [comment]
Closing this for now. Please reopen if you intend to do any more work on this.

**Pull request closed without merging**
