### PR TITLE
Dependency updates for master

### PR DESCRIPTION
**Pull request by Lex-2008**
Update lcov from 1.14 to 1.15
Update lmdb from 0.9.28 to 0.9.29
Update openssl from 1.1.1i to 1.1.1k
Update openldap from 2.4.57 to 2.4.58
Update libattr from 2.4.48 to 2.5.1
Update libacl from 2.2.53 to 2.3.1
Update git from 2.30.1 to 2.31.1

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a PR! Maybe @craigcomstock can review this?

**Comment by Lex-2008** [comment]
this lacks PHP

**Comment by Lex-2008** [comment]
@cf-bottom build exotics

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6448/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6448/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6448/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6448/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6448/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6448/

**Comment by Lex-2008** [comment]
@cf-bottom build exotics

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6509/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6509/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6509/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6510/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6510/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6510/

**Comment by Lex-2008** [comment]
@cf-bottom build exotics

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6525/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6525/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6525/

**Pull request merged**
