### PR TITLE
Kill debug_and_release and other BUILD_TYPEs.

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by jimis** [comment]
Maybe merge after 3.6.4.

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
The test build failed because it has to be accompanied by a simple change in autobuild, that changes jenkins testing build from "quick" to "debug" and release build from "debug_and_release" to "release".

**Comment by kacfengine** [comment]
Yep, let's merge this as soon as the release is out.

**Comment by jimis** [comment]
Rebased, will merge on Monday.

**Pull request merged**
