### PR TITLE
Dependency updates for 3.12.x

### PR DESCRIPTION
**Pull request by Lex-2008**
Update libcurl-hub from 7.66.0 to 7.67.0
Update git from 2.21.0 to 2.24.0
Update postgresql from 10.10 to 10.11
Update libcurl from 7.66.0 to 7.67.0

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom build this on exotics, also, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4168/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4168/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4168/

**Comment by Lex-2008** [comment]
builds are :green_apple:, ok to review!
https://ci.cfengine.com/job/pr-pipeline/4174/ - LINUX
https://ci.cfengine.com/job/pr-pipeline/4184/ - EXOTICS

**Comment by Lex-2008** [comment]
no, wait

**Comment by Lex-2008** [comment]
@cf-bottom build it

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4194/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4194/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4194/

**Comment by Lex-2008** [comment]
green enough

**Pull request merged**
