### PR TITLE
ENT-6015 Added various fixes for packaging from master (3.12.x)

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5207/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5207/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5207/

**Comment by Lex-2008** [comment]
Hmm... These commits were for a "use non-standard prefix instead of /var/cfengine" task, and I didn't backport them to 3.12.x because they didn't fix any bug... and don't actually bring anything useful, at least for us :) Do you want to bring them to 3.12.x so future backports didn't raise merge conflicts and go smoother?

**Comment by craigcomstock** [comment]
@Lex-2008 looks like I missed (or didn't push) the fix I was really aiming for. I cherry-picked so many to reduce conflicts and such. :| Will re-try.

**Comment by craigcomstock** [comment]
Will let @Lex-2008 take this.

**Pull request closed without merging**
