### PR TITLE
Dependency updates for 3.12.x

### PR DESCRIPTION
**Pull request by Lex-2008**
Update lcov from 1.13 to 1.14
Update lmdb from 0.9.22 to 0.9.23
Update pcre from 8.42 to 8.43
Update libxml2 from 2.9.8 to 2.9.9
Update libyaml from 0.2.1 to 0.2.2
Update openldap from 2.4.46 to 2.4.47
Update libcurl-hub from 7.62.0 to 7.64.1
Update apr from 1.6.5 to 1.7.0
Update apache from 2.4.35 to 2.4.39
Update git from 2.19.1 to 2.21.0
Update postgresql-hub from 10.6 to 10.7
Update php from 7.2.12 to 7.2.18
Update libcurl from 7.62.0 to 7.64.1
Update OpenSSL from 1.1.0i to 1.1.1b

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a PR! Maybe @craigcomstock can review this?

**Comment by Lex-2008** [comment]
@cf-bottom ask jenkins to give me a cookie

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2425/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2425/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2425/

**Comment by Lex-2008** [comment]
@cf-bottom build again

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2426/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2426/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2426/

**Comment by Lex-2008** [comment]
@vpodzime : should I ask Tom to make a new build?

**Comment by Lex-2008** [comment]
@cf-bottom make build green!

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2429/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2429/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2429/

**Comment by Lex-2008** [comment]
Merging it while it's green: https://ci.cfengine.com/job/pr-pipeline/2464/

**Pull request merged**
