### PR TITLE
3.12.x PR

### PR DESCRIPTION
**Pull request by Lex-2008**

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom build it, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4016/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4016/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4016/

**Comment by Lex-2008** [comment]
@cf-bottom build again

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4019/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4019/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4019/

**Pull request merged**
