### PR TITLE
Dependency updates for master

### PR DESCRIPTION
**Pull request by Lex-2008**
Update openssl from 1.1.1l to 3.0.3
Update libiconv from 1.16 to 1.17
Update libcurl-hub from 7.83.0 to 7.83.1
Update git from 2.36.0 to 2.36.1
Update postgresql from 14.2 to 14.3
Update libcurl from 7.83.0 to 7.83.1
Update openldap from 2.6.1 to 2.6.2
Update php from 8.0.19 to 8.1.7

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom build exotics

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8015/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8015/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8015/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8025/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8025/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8025/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8088/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8088/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8088/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8148/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8148/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8148/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8149/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8149/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8149/

**Pull request merged**
