### PR TITLE
Show more output from test

### PR DESCRIPTION
**Pull request by nickanderson**
Merge together:
https://github.com/cfengine/core/pull/4196
https://github.com/cfengine/enterprise/pull/619

### CODE REVIEW

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5191/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5191/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5191/

**Comment by nickanderson** [comment]
@cf-bottom jenkins, again, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5192/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5192/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5192/

**Pull request closed without merging**
