### PR TITLE
openssl-1.0.2a TEST BUILD

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by jimis** [comment]
do not merge, I'll be triggering several builds.

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
This is ready to be merged, once master is green again (it is failing because of irrelevant package promises failures). Please review since there are a bunch of changes in there, great simplifications have taken place.

**Comment by kacfengine** [comment]
This is great! So much cruft removed!

**Comment by kacfengine** [comment]
> it is failing because of irrelevant package promises failures

Hopefully fixed by https://github.com/cfengine/masterfiles/commit/ad16c7e2bc51b8fb435a81b5cf152ab41095b057.

**Comment by kacfengine** [comment]
Cherry-picked to 3.7.x as well.

**Pull request merged**
