### PR TITLE
Upgrade to LMDB 0.9.14.

### PR DESCRIPTION
**Pull request by kacfengine**
https://dev.cfengine.com/issues/6357

### CODE REVIEW

**Comment by kacfengine** [comment]
trigger build

**Comment by jimis** [comment]
Is that all it's needed? What about the `cfbuild-lmdb.spec` file? And what about all our current patches? I'm quite sure some are not needed, e.g. support for robust mutexes has been merged upstream IIRC.

**Comment by kacfengine** [comment]
No, it isn't. :-) In fact much more is needed! Hallvard has made a proper robust patch, but unfortunately it is not in the master branch, so we will need to do patching onto the 0.9.14 version. I'm still working on this.

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
Build green for all platforms but AIX, presumably because of a missing distfile download. Will try again.

**Comment by kacfengine** [comment]
Finally, after 22 "Trigger builds!" :-)

**Pull request merged**
