### PR TITLE
3.21.x deps 2023 12 15 16 02 13 345202

### PR DESCRIPTION
**Pull request by larsewi**
* Updated openssl from 3.0.10 to 3.0.12
* Updated libxml2 from 2.11.5 to 2.12.3
* Updated libcurl-hub from 8.2.1 to 8.5.0
* Updated apache from 2.4.57 to 2.4.58
* Updated git from 2.42.0 to 2.43.0
* Updated postgresql from 15.4 to 15.5
* Updated libcurl from 8.2.1 to 8.5.0
* Updated php from 3.2.9 to 3.2.13
* Updated automake from 1.10.1 to 1.10.3
* Updated libgcc from 4.2.0 to 4.2.4
* Updated libtool from 1.5.24 to 1.5.26

### CODE REVIEW

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10177/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10177/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10177/

**Comment by larsewi** [comment]
@cf-bottom Jenkins with exotics please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10179/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10179/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10179/

**Review by craigcomstock — APPROVED** [review]

**Comment by aleksandrychev** [comment]
@larsewi PHP 8.3 is a major update, afaik we do minor only in the patch releases

**Comment by vpodzime** [comment]
> @larsewi PHP 8.3 is a major update, afaik we do minor only in the patch releases

Last time we did this: *Updated php from 8.1.12 to 8.2.9*

**Comment by vpodzime** [comment]
> Updated lcov from 1.16 to 2.0

This is definitely a major update, though.

**Comment by aleksandrychev** [comment]
> > @larsewi PHP 8.3 is a major update, afaik we do minor only in the patch releases
> 
> Last time we did this: _Updated php from 8.1.12 to 8.2.9_

that was a major update as well :)

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10186/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10186/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10186/

**Comment by aleksandrychev** [comment]
@cf-bottom Jenkins with exotics again please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10199/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10199/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10199/

**Comment by vpodzime** [comment]
>  ci/testing_pr/PACKAGES_sparc64_solaris_11 — Build finished: failure 

SSH failure. Retry on this platform only: [Build Status](https://ci.cfengine.com/job/pr-pipeline/10201/)

**Review by aleksandrychev — APPROVED** [review]

**Comment by larsewi** [comment]
@cf-bottom Jenkins with exotics please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10205/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10205/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10205/

**Comment by larsewi** [comment]
[Build Status](https://ci.cfengine.com/job/pr-pipeline/10208/)

**Review by vpodzime — APPROVED** [review]
ACK

**Pull request merged**
