### PR TITLE
Dependency updates for master

### PR DESCRIPTION
**Pull request by Lex-2008**
Update openssl from 1.1.1f to 1.1.1g
Update libyaml from 0.2.2 to 0.2.5
Update openldap from 2.4.49 to 2.4.50
Update libcurl-hub from 7.68.0 to 7.70.0
Update apache from 2.4.41 to 2.4.43
Update git from 2.25.1 to 2.27.0
Update postgresql from 12.2 to 12.3
Update php from 7.4.2 to 7.4.6
Update libcurl from 7.68.0 to 7.70.0

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom build it including exotics

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5215/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5215/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5215/

**Comment by Lex-2008** [comment]
@cf-bottom build exotics once again, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5253/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5253/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5253/

**Pull request merged**
