### PR TITLE
3.10.x deps update including libxml2 huge_val patch

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
https://ci.cfengine.com/job/pr-pipeline/333/
label.contains('sparc') so only run on sparc platforms for now.

**Comment by vpodzime** [comment]
> https://ci.cfengine.com/job/pr-pipeline/333/
> label.contains('sparc') so only run on sparc platforms for now.

All green, nice @craigcomstock! The ``INFINITY``-related patch looks good to me. Haven't checked the rest yet.

**Comment by vpodzime** [comment]
@craigcomstock I think we already have all these changes applied, right?

**Comment by craigcomstock** [comment]
Yes. Here I believe: https://github.com/cfengine/buildscripts/commit/9dfce7d13a55e16c79931c8dfdb9c06e64dd7b62

**Pull request closed without merging**
