### PR TITLE
Updated libxml2 from 2.9.14 to 2.10.3

### PR DESCRIPTION
**Pull request by Lex-2008**
Updated libxml2 from 2.9.14 to 2.10.3

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom build exotics if you can

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8929/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8929/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8929/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8930/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8930/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8930/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8934/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8934/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8934/

**Pull request merged**
