### PR TITLE
Change: Switch SSL Key Size back to 2048

### PR DESCRIPTION
**Pull request by nickanderson**
4096 bit key is overkill. It doesn't offer double the security, but it is
costs computationally more than double. See here:
https://www.gnupg.org/faq/gnupg-faq.html#please_use_ecc

### CODE REVIEW

**Comment by nickanderson** [comment]
@jimis & @estenberg

**Comment by jimis** [comment]
+1 from my point of view. @estenberg lets prioritise supporting ECC keys in CFEngine (both MP and agent) instead.

**Comment by nickanderson** [comment]
FYI I also updated the PR to masterfiles to mustachify the httpd config since I added a bundle to generate the cert as well.

**Comment by nickanderson** [comment]
@estenberg what's the verdict here, shall we switch back to 2048 bit ssl keys?

**Comment by nickanderson** [comment]
ping @estenberg

**Comment by estenberg** [comment]
I would just leave it to 4096. I don't think there are any resource issues with this and it takes us above 128 bits of security which makes AES the weakest link not RSA.

Sure ECC would be nice but that is a bigger undertaking entirely and why do we need more bits of security for this?

**Comment by nickanderson** [comment]
OK then closing this PR.

**Pull request closed without merging**
