### PR TITLE
3.7.x deps update including libxml2 huge_val patch 

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
ole and vratislav, does my patch look OK? Seems right according to the research I did: https://tracker.mender.io/browse/ENT-3721?focusedCommentId=87851&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-87851

**Comment by craigcomstock** [comment]
https://ci.cfengine.com/job/pr-pipeline/328/

**Comment by olehermanse** [comment]
My understanding is very limited, I'll defer to @vpodzime.

**Comment by craigcomstock** [comment]
try 2 - https://ci.cfengine.com/view/PR%20Pipeline/job/pr-pipeline/330/

**Comment by vpodzime** [comment]
@craigcomstock I think we already have all these changes applied, right?

**Comment by craigcomstock** [comment]
Yes. Already merged: https://github.com/cfengine/buildscripts/commit/7de3bf532f671ab9d532f8f511b13764abc8421c

**Pull request closed without merging**
