### PR TITLE
Dependency updates for master

### PR DESCRIPTION
**Pull request by Lex-2008**
Update lmdb from 0.9.23 to 0.9.24
Update openssl from 1.1.1b to 1.1.1c
Update openldap from 2.4.47 to 2.4.48
Update libcurl-hub from 7.64.1 to 7.65.3
Update apache from 2.4.39 to 2.4.41
Update git from 2.21.0 to 2.23.0
Update postgresql from 12beta2 to 12beta3
Update php from 7.3.5 to 7.3.8
Update libcurl from 7.64.1 to 7.65.3

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a PR! Maybe @craigcomstock can review this?

**Comment by Lex-2008** [comment]
@cf-bottom please build, including exotics, hoping they are back online for real

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2670/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2670/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2670/

**Comment by Lex-2008** [comment]
rebuild: https://ci.cfengine.com/job/pr-pipeline/2686/

**Comment by Lex-2008** [comment]
still building: https://ci.cfengine.com/job/pr-pipeline/2706/

**Comment by Lex-2008** [comment]
@cf-bottom make the green build, including exotics, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2716/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2716/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2716/

**Comment by Lex-2008** [comment]
Ready to be reviewed!

Note that openldap commit also defines `HOST_NAME_MAX 63` on hp-ux (this const is required later in the code, and 63 is the value that `getent HOST_NAME_MAX` prints on our buildslave)

**Comment by vpodzime** [comment]
> this const is required later in the code, and 63 is the value that `getent HOST_NAME_MAX` prints on our buildslave
```
bash-4.3$ getent HOST_NAME_MAX
bash: getent: command not found
```

**Comment by vpodzime** [comment]
> Alright, I triggered a build:
> 
> [Build Status](https://ci.cfengine.com//job/pr-pipeline/2716/)

Some spurious failure in the new bootstrap tests. Everything else is green so :+1:

**Comment by Lex-2008** [comment]
my bad, it was
```
$ getconf HOST_NAME_MAX
63
```
-- took it from http://www.softpanorama.org/DNS/maximum_hostname_length.shtml

**Pull request merged**
