### PR TITLE
Master dependency upgrades

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7317/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7317/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7317/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics, I tested locally with vagrant-ci and build-remote mingw style and both worked for install-dependencies step, so hopefully is nearly there.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7318/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7318/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7318/

**Comment by craigcomstock** [comment]
bootstrap-tests failure should be fixed with https://tracker.mender.io/browse/ENT-7966 (https://github.com/cfengine/buildscripts/pull/888 merged)

Solaris failures seem similar to other failures recently: https://tracker.mender.io/browse/INF-2303

@Lex-2008 you want to review and see about merging?

**Review by Lex-2008 — APPROVED** [review]

**Comment by craigcomstock** [comment]
One more change needs to be cherry picked back to 3.15.x and 3.18.x in pkg-get-src which uses desired filename instead of `download` for sourceforge deps.

a9869e476e7e78a32da5f6ee93a4f1d5d3eee545

**Pull request merged**
