### PR TITLE
ENT-10347: Added Debian 12 label to buildscripts

### PR DESCRIPTION
**Pull request by larsewi**
Merge together with:
 - https://github.com/mendersoftware/infra/pull/382
 - https://github.com/cfengine/system-testing/pull/506
 - https://github.com/cfengine/core/pull/5363

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a PR! Maybe @craigcomstock can review this?

**Comment by larsewi** [comment]
[Build Status](https://ci.cfengine.com/job/pr-pipeline/10002/)

**Comment by larsewi** [comment]
[Build Status](https://ci.cfengine.com//job/pr-pipeline/10029/)

**Review by vpodzime — APPROVED** [review]
ACK

**Pull request merged**
