### PR TITLE
ENT-4557 fix migration scripts

### PR DESCRIPTION
**Pull request by Lex-2008**

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom build this, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2385/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2385/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2385/

**Comment by Lex-2008** [comment]
@cf-bottom : that build was wrong

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2405/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2405/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2405/

**Comment by Lex-2008** [comment]
tested upgrading 3.12.0 vagrant hub to redhat_6 hub from last cf-bottom's comment, works good! @vpodzime : please approve and we can merge

**Comment by vpodzime** [comment]
> please approve and we can merge

DONE. Does it need to be backported to 3.12.x too?

**Pull request merged**
