### PR TITLE
Dependency updates for master

### PR DESCRIPTION
**Pull request by Lex-2008**
Update openssl from 1.1.1b to 1.1.1c
Update libcurl-hub from 7.64.1 to 7.65.1
Update git from 2.21.0 to 2.22.0
Update php from 7.3.5 to 7.3.6
Update libcurl from 7.64.1 to 7.65.1

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a pull request! Maybe @craigcomstock can review this?

**Comment by Lex-2008** [comment]
@cf-bottom build exotics

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2662/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2662/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2662/

**Comment by olehermanse** [comment]
I don't think this is necessary for 3.14.0.

**Pull request closed without merging**
