### PR TITLE
Introduce --test-shell option to build-remote.

### PR DESCRIPTION
**Pull request by kacfengine**

### CODE REVIEW

**Comment by kacfengine** [comment]
@jimis: I haven't tested this yet, but it's here to try if you want. I'll test it soon on a "when-I-need-to-use-it" basis.

**Comment by jimis** [comment]
+1

**Comment by kacfengine** [comment]
trigger build

**Comment by kacfengine** [comment]
This worked nicely in my testing, but I'll keep this in master. @jimis: Feel free to try ``--test-shell`` next time you need access to the chroot to debug a test on a build machine!

**Pull request merged**
