### PR TITLE
Do not install python 2 version and Updated Node.js version to 20 in the CI

### PR DESCRIPTION
**Pull request by aleksandrychev**

### CODE REVIEW

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10878/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10878/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10878/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10879/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10879/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10879/

**Review by craigcomstock — CHANGES_REQUESTED** [review]
I am pretty certain that psycopg2 is a dependency for nova reporting tests which seem to already be adjusted for python3 but you should probably do the same thing you did for mission-portal and trigger gh actions in nova.

**Comment by aleksandrychev** [comment]
> I am pretty certain that psycopg2 is a dependency for nova reporting tests which seem to already be adjusted for python3 but you should probably do the same thing you did for mission-portal and trigger gh actions in nova.

good point, done https://github.com/cfengine/nova/pull/2254

**Comment by aleksandrychev** [comment]
> I am pretty certain that psycopg2 is a dependency for nova reporting tests which seem to already be adjusted for python3 but you should probably do the same thing you did for mission-portal and trigger gh actions in nova.

tests

**Review by craigcomstock — APPROVED** [review]

**Pull request merged**
