### PR TITLE
ENT-10673: Upgrade cfbs to 3.2.11 to fix cfbs-shell test failures

### PR DESCRIPTION
**Pull request by craigcomstock**
The use of cfbs init --masterfiles=master was broken due to 3.21.2 steps trying to delete non-existing files/paths.

Ticket: ENT-10673
Changelog: none

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9879/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9879/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9879/

**Comment by craigcomstock** [comment]
cherry pick to 3.21.x required some "catching up" : https://github.com/cfengine/buildscripts/pull/1293

**Review by nickanderson — APPROVED** [review]
Looks right to me.

**Comment by craigcomstock** [comment]
el8 jenkins failure is known issue, restorecon https://northerntech.atlassian.net/browse/ENT-9592

**Pull request merged**
