### PR TITLE
ENT-7741 Upgrade diffutils 3.7 to 3.8 and add '-pthread' linker option on AIX 

### PR DESCRIPTION
**Pull request by craigcomstock**
Ticket: ENT-7741
Changelog: none

### CODE REVIEW

**Comment by craigcomstock** [comment]
try this again with proper version 3.8 instead of 3.7

[Build Status](https://ci.cfengine.com/job/pr-pipeline/7301/)

**Comment by craigcomstock** [comment]
duh, didn't change distfiles, will try again :)

**Comment by craigcomstock** [comment]
aix 53 and 71 are green :+1:

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7306/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7306/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7306/

**Review by Lex-2008 — APPROVED** [review]

**Pull request merged**
