### PR TITLE
CFE-3133: Built packages now include mdb_load and mdb_copy lmdb utilities (3.12)

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom build this in jenkins, please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2930/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2930/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2930/

**Comment by vpodzime** [comment]
Looks like this is failing in jenkins.

**Comment by olehermanse** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2934/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2934/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2934/

**Comment by olehermanse** [comment]
> Looks like this is failing in jenkins.

@vpodzime yep. Working with these patches is annoying. I should have made the commits in master easier to cherry-pick. Should be fixed now!

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2935/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2935/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2935/

**Pull request merged**
