### PR TITLE
Fixed PHP and JS dependencies permissions

### PR DESCRIPTION
**Pull request by aleksandrychev**
ChangeLog: None

Ticket: ENT-5721

### CODE REVIEW

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5106/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5106/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5106/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5107/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5107/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5107/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5110/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5110/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5110/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5111/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5111/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5111/

**Comment by craigcomstock** [comment]
re-trying fr-tests, bootstrap-tests, sequential-tests, I'm pretty sure they all failed due to bad DNS preventing AWS spawning.

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5112/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5112/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5112/

**Comment by craigcomstock** [comment]
Our debian-8 turn-back-time strategy is failing bootstrap-tests for this PR. I will work on fixing debian-8. After that will retry bootstrap-tests with this package and hopefully we'll be green and can merge. Manual testing on centos-6 and debian-8 hubs looked fine.

**Comment by craigcomstock** [comment]
re-ran two jobs from 5112 job above and consider this green so will merge.

https://ci.cfengine.com/job/testing-run-php-tests/167/
https://ci.cfengine.com/job/bootstrap-tests/1202/

**Comment by craigcomstock** [comment]
@vpodzime mentioned in the ticket that 3.15.1 might be affected as well. So investigate 3.15.x fix also?

**Comment by craigcomstock** [comment]
I am fairly certain that issues with 3.15.x were due to debian8 host time traveling. 3.15.x doesn't have the migration to vendor/public that occurred so does not need this commit.

**Comment by olehermanse** [comment]
@craigcomstock so I see this was merged with a `squashme` commit. In the future, could you try to just amend the commit, i.e. not use `squashme` or `WIP` commits at all? That way, there is no "extra step" (squashing) that you can forget to do. (Unless the commit is actually a WIP and could never be merged, because it needs more work).

**Pull request merged**
