### PR TITLE
ENT-11212: Do not ship ldap and api unit tests in release packages

### PR DESCRIPTION
**Pull request by aleksandrychev**
Ticket: ENT-11212

### CODE REVIEW

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10876/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10876/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10876/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10877/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10877/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10877/

**Review by craigcomstock — APPROVED** [review]

**Comment by aleksandrychev** [comment]
@craigcomstock please merge this and cherry picks https://github.com/cfengine/buildscripts/pull/1442 https://github.com/cfengine/buildscripts/pull/1441

**Comment by craigcomstock** [comment]
sequential tests failure should have been marked known issue, ENT-11814 which may be resolved as of yesterday so OK to merge.

**Pull request merged**
