### PR TITLE
Add cf-net to windows packaging

### PR DESCRIPTION
**Pull request by olehermanse**
Merge with: cfengine/enterprise#338

### CODE REVIEW

**Comment by olehermanse** [comment]
https://github.com/cfengine/enterprise/pull/338

**Comment by olehermanse** [comment]
Jenkins:
https://ci.cfengine.com/job/bootstrap-enterprise-pr/349/
https://ci.cfengine.com/job/testing-enterprise-pr/325/

**Comment by olehermanse** [comment]
Jenkins:
https://ci.cfengine.com/job/bootstrap-enterprise-pr/350/
https://ci.cfengine.com/job/testing-enterprise-pr/326/

**Comment by olehermanse** [comment]
Tested, works. Discovered some issues with cf-net on windows that I'll work on next.

@jimis Please merge this with cfengine/enterprise#338

**Comment by jimis** [comment]
/me bows down to our new windows overlord, @olehermanse !

**Pull request merged**
