### PR TITLE
ENT-5063 Fix state/pg perms

### PR DESCRIPTION
**Pull request by Lex-2008**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a PR! Maybe @craigcomstock can review this?

**Comment by Lex-2008** [comment]
I believe we can't change permissions in the RPM because "cfpostgres" user might not exist while rpm extracts files before postinst script is running.

**Comment by vpodzime** [comment]
> I believe we can't change permissions in the RPM because "cfpostgres" user might not exist while rpm extracts files before postinst script is running.

Ownership is one thing, permissions are another thing. The commands moved in this PR change both so I wonder if there is something wrong with the **permissions** in the RPM.

**Comment by Lex-2008** [comment]
I see that you can have `%defattr(755,root,root,755)` in *.spec file, but I don't see anything similar in `debian/*.install` file. So let's keep it like this, and find a proper fix in a future - https://tracker.mender.io/browse/ENT-4267

**Pull request merged**
