### PR TITLE
ENT-12312: master deps 2024 12 11 17 37 16 928850

### PR DESCRIPTION
**Pull request by larsewi**
[Build Status](https://ci.cfengine.com/job/pr-pipeline/11536/)

### CODE REVIEW

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/11504/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/11504/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-11504/

**Review by craigcomstock — APPROVED** [review]
excellent! thanks for remembering the deps table on master only. :+1:

**Comment by craigcomstock** [comment]
deb11hub package failed due to compilation error, maybe memory issue, segfault with CC.

**Comment by craigcomstock** [comment]
retrying just deb11hub after adding a capture of journalctl on failure: [Build Status](https://ci.cfengine.com/job/pr-pipeline/11539/)

**Comment by craigcomstock** [comment]
retry deb11hub after adding coredumpctl to testing-pr on failure and systemd-coredump package to build host policy.
[Build Status](https://ci.cfengine.com/job/pr-pipeline/11541/)

**Comment by craigcomstock** [comment]
retry, testing-pr scripts not quite right

[Build Status](https://ci.cfengine.com/job/pr-pipeline/11542/)

**Comment by craigcomstock** [comment]
increased size of deb11 buildhost instances. retry:

[Build Status](https://ci.cfengine.com/job/pr-pipeline/11543/)

**Comment by larsewi** [comment]
Let's try even bigger! Someone on a forum said it's likely due to too little resources.

[Build Status](https://ci.cfengine.com/job/pr-pipeline/11549/)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/11551/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/11551/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-11551/

**Comment by craigcomstock** [comment]
ci/jenkins looking good to me! I will try to merge...

**Pull request merged**
