### PR TITLE
Dependency updates for master

### PR DESCRIPTION
**Pull request by Lex-2008**
Update lcov from 1.13 to 1.14
Update lmdb from 0.9.22 to 0.9.23
Update pcre from 8.42 to 8.43
Update sasl2 from 2.1.26 to 2.1.27
Update libiconv from 1.15 to 1.16
Update libxml2 from 2.9.8 to 2.9.9
Update libyaml from 0.2.1 to 0.2.2
Update openldap from 2.4.46 to 2.4.47
Update libcurl-hub from 7.61.1 to 7.64.1
Update apr from 1.6.5 to 1.7.0
Update apache from 2.4.35 to 2.4.39
Update postgresql-hub from 11.0 to 11.3
Update php from 7.2.11 to 7.3.5
Update libcurl from 7.61.1 to 7.64.1
Update OpenSSL from 1.1.1 to 1.1.1b 
Update git from 2.19.1 to 2.21.0

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a PR! Maybe @craigcomstock can review this?

**Comment by Lex-2008** [comment]
@cf-bottom build it, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2524/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2524/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2524/

**Comment by vpodzime** [comment]
@cf-bottom jenkins with exotics, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2541/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2541/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2541/

**Comment by vpodzime** [comment]
Jenkins builds:
https://ci.cfengine.com/job/testing-pr/3732/ (AIX 5 timed out, green otherwise)
https://ci.cfengine.com/job/testing-pr/3738/ (AIX 5 only, green)

**Comment by Lex-2008** [comment]
Since I can't approve my own PRs, here's the seal:

ok

**Pull request merged**
