### PR TITLE
ENT-9685: Added selinux policy source files and instructions on how to use them (3.21)

### PR DESCRIPTION
**Pull request by craigcomstock**
with https://github.com/cfengine/core/pull/5160

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9166/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9166/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9166/

**Comment by craigcomstock** [comment]
sequential-tests triple-upgrade failed with maybe a legitimate selinux issue: https://tracker.mender.io/browse/ENT-9775

**Comment by craigcomstock** [comment]
rhel-8 client selinux failure during triple upgrade test is maybe a flake? Couldn't reproduce manually... so retrying the automated test: [Build Status](https://ci.cfengine.com/job/sequential-tests/5172/)

**Comment by craigcomstock** [comment]
another run is green, so will mark that selinux issue as flaky and follow-up/monitor for another occurrence.

**Pull request merged**
