### PR TITLE
ENT-3336: Ensure Enterprise Hub package upgrade aborts when unable to backup database

### PR DESCRIPTION
**Pull request by nickanderson**

### CODE REVIEW

**Comment by nickanderson** [comment]
@Lex-2008 @jimis

**Comment by Lex-2008** [comment]
Removing `cd` looks scary. Let me request Jenkins build (and a deployment test run) before you merge this

**Comment by nickanderson** [comment]
Cool thanks

**Comment by nickanderson** [comment]
I like your use of badge

**Comment by nickanderson** [comment]
When i drill down it all looks like python stuff, I don't see anything that I recognize.

2017-08-24_selection_017

**Comment by Lex-2008** [comment]
Cleaning up those messages is on my list, indeed.

After looking at the logs, looks like indeed there is some issue in the packaging script:
````
[165.227.52.42] installing package cfengine-nova-hub_3.12.0a.627b6c4~384_amd64.deb on host [165.227.52.42]
[165.227.52.42] sudo: dpkg -i /var/tmp/cfengine-nova-hub_3.12.0a.627b6c4~384_amd64.deb
[165.227.52.42] out: Selecting previously unselected package cfengine-nova-hub.
[165.227.52.42] out: (Reading database ... 35412 files and directories currently installed.)
[165.227.52.42] out: Preparing to unpack .../cfengine-nova-hub_3.12.0a.627b6c4~384_amd64.deb ...
[165.227.52.42] out: dpkg: error processing archive /var/tmp/cfengine-nova-hub_3.12.0a.627b6c4~384_amd64.deb (--install):
[165.227.52.42] out:  subprocess new pre-installation script returned error exit status 2
[165.227.52.42] out: Errors were encountered while processing:
[165.227.52.42] out:  /var/tmp/cfengine-nova-hub_3.12.0a.627b6c4~384_amd64.deb
[165.227.52.42] out: 
Fatal error: sudo() received nonzero return code 1 while executing!
Requested: dpkg -i /var/tmp/cfengine-nova-hub_3.12.0a.627b6c4~384_amd64.deb
Aborting.
````
Basically it's saying that pre-installation script returned error exit status 2. That's for PACKAGES_HUB_x86_64_linux_debian_7 on debian-8-x64. I'm wondering if we can increase verbosity of the script. Maybe `set -ex`?

**Comment by nickanderson** [comment]
@Lex-2008 I made a couple small tweaks can you send it through the gauntlet?

**Comment by Lex-2008** [comment]
Builds away!
Bootstrap: [Build Status](https://ci.cfengine.com/job/bootstrap-enterprise-pr/412/)
Testing: [Build Status](https://ci.cfengine.com/job/testing-enterprise-pr/385/) (projected)
Deploytests: [Build Status](https://ci.cfengine.com/job/testing-run-deployment-tests/387/) (projected)

**Comment by nickanderson** [comment]
Thanks!

**Comment by Lex-2008** [comment]
Nope, sorry Nick, it's still unhappy:

Both on CentOS:
````
[138.197.223.168] installing package cfengine-nova-hub-3.12.0a.627b6c4-385.x86_64.rpm on host [138.197.223.168]
[138.197.223.168] sudo: rpm -U /var/tmp/cfengine-nova-hub-3.12.0a.627b6c4-385.x86_64.rpm
[138.197.223.168] out: error: %pre(cfengine-nova-hub-3.12.0a.627b6c4-385.x86_64) scriptlet failed, exit status 1
[138.197.223.168] out: error:   install: %pre scriptlet failed (2), skipping cfengine-nova-hub-3.12.0a.627b6c4-385
[138.197.223.168] out: 

Fatal error: sudo() received nonzero return code 1 while executing!

Requested: rpm -U /var/tmp/cfengine-nova-hub-3.12.0a.627b6c4-385.x86_64.rpm
Executed: env /bin/sh -c "rpm -U /var/tmp/cfengine-nova-hub-3.12.0a.627b6c4-385.x86_64.rpm"

Aborting.
````

And on Debian:
````
[165.227.56.166] installing package cfengine-nova-hub_3.12.0a.627b6c4~385_amd64.deb on host [165.227.56.166]
[165.227.56.166] sudo: dpkg -i /var/tmp/cfengine-nova-hub_3.12.0a.627b6c4~385_amd64.deb
[165.227.56.166] out: Selecting previously unselected package cfengine-nova-hub.
[165.227.56.166] out: (Reading database ... 30419 files and directories currently installed.)
[165.227.56.166] out: Unpacking cfengine-nova-hub (from .../cfengine-nova-hub_3.12.0a.627b6c4~385_amd64.deb) ...
[165.227.56.166] out: dpkg: error processing /var/tmp/cfengine-nova-hub_3.12.0a.627b6c4~385_amd64.deb (--install):
[165.227.56.166] out:  subprocess new pre-installation script returned error exit status 2
[165.227.56.166] out: Errors were encountered while processing:
[165.227.56.166] out:  /var/tmp/cfengine-nova-hub_3.12.0a.627b6c4~385_amd64.deb
[165.227.56.166] out: 
Fatal error: sudo() received nonzero return code 1 while executing!

Requested: dpkg -i /var/tmp/cfengine-nova-hub_3.12.0a.627b6c4~385_amd64.deb
Executed: env /bin/sh -c "dpkg -i /var/tmp/cfengine-nova-hub_3.12.0a.627b6c4~385_amd64.deb"

Aborting.
````

**Comment by nickanderson** [comment]
Hurmm
[165.227.56.166] out:  subprocess new pre-installation script returned error exit status 2

Can we see what is contained in the hub install log under /var/log contains?

**Comment by Lex-2008** [comment]
I took over this issue and created https://github.com/cfengine/buildscripts/pull/275

**Pull request closed without merging**
