### PR TITLE
ENT-11054: Bumped cfbs version to 3.2.12

### PR DESCRIPTION
**Pull request by aleksandrychev**
Ticket: ENT-11054

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10172/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10172/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10172/

**Comment by aleksandrychev** [comment]
@olehermanse please merge, I have no access

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10212/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10212/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10212/

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10234/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10234/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10234/

**Comment by olehermanse** [comment]
GH Actions is due to missing secrets (fixed separately, the pipeline shouldn't run for this PR).

Rest of CI looks green.

**Review by olehermanse — APPROVED** [review]

**Pull request merged**
