### PR TITLE
explicitly set PKG_CONFIG_PATH

### PR DESCRIPTION
**Pull request by Lex-2008**
otherwise, we pick wrong pkg-config file

Ticket: ENT-9059

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a PR! Maybe @craigcomstock can review this?

**Comment by Lex-2008** [comment]
:green_circle: Solaris-only build: https://ci.cfengine.com/job/pr-pipeline/8472/
build to check that other platofrms survive this: https://ci.cfengine.com/job/pr-pipeline/8475/

**Review by vpodzime — COMMENTED** [review]
*"...tha~t~n we would like to have"* in the commit message. Looks good to me otherwise.

**Comment by Lex-2008** [comment]
No need to cherry-pick, since original issue was on master only

**Pull request merged**
