### PR TITLE
ENT-8223 try to debug early segfault in httpd

### PR DESCRIPTION
**Pull request by craigcomstock**
merge together
https://github.com/cfengine/masterfiles/pull/2174
https://github.com/cfengine/buildscripts/pull/921

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7397/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7397/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7397/

**Comment by craigcomstock** [comment]
for grins, lets see if `ulimit -c unlimited` in the preinstall script helps at all. @cf-bottom jenkins again now.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7398/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7398/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7398/

**Pull request closed without merging**
