### PR TITLE
Minor dependency updates (3.24)

### PR DESCRIPTION
**Pull request by craigcomstock**
- **Updated openssl from 3.3.2 to 3.4.0**
- **Updated php from 8.3.12 to 8.3.13**
with https://github.com/cfengine/system-testing/pull/579

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/11332/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/11332/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-11332/

**Comment by craigcomstock** [comment]
didn't notice that mingw rules included the patch, figured it was "automatic" *.patch.

retry: [Build Status](https://ci.cfengine.com/job/pr-pipeline/11336/)

**Comment by craigcomstock** [comment]
mingw testing-pr is green, will test the package manually while waiting for CI...

**Comment by craigcomstock** [comment]
Will retry a full run after I make adjustments to system-testing to improve ssh reliability.

**Comment by craigcomstock** [comment]
waiting for master deps CI at https://github.com/cfengine/buildscripts/pull/1518 to be green, then will proceed with this PR (which includes deployment test stability changes)

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/11357/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/11357/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-11357/

**Comment by craigcomstock** [comment]
green enough

**Pull request merged**
