### PR TITLE
ENT-11573: Added leech to deps-packaging

### PR DESCRIPTION
**Pull request by larsewi**
Ticket: [ENT-11573](https://northerntech.atlassian.net/browse/ENT-11573)
Changelog: None
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>

[ENT-11573]: https://northerntech.atlassian.net/browse/ENT-11573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10619/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10619/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10619/

**Comment by larsewi** [comment]
[Build Status](https://ci.cfengine.com/job/pr-pipeline/10622/configure)

**Comment by larsewi** [comment]
[Build Status](https://ci.cfengine.com/job/pr-pipeline/10623/)

**Comment by larsewi** [comment]
[Build Status](https://ci.cfengine.com/job/pr-pipeline/10624/)

**Comment by larsewi** [comment]
@cf-bottom jenkins with exotics please :)

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10654/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10654/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10654/

**Comment by larsewi** [comment]
@cf-bottom jenkins with exotics please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10656/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10656/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10656/

**Comment by larsewi** [comment]
@cf-bottom jenkins with exotics please :)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10657/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10657/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10657/

**Comment by larsewi** [comment]
[Build Status](https://ci.cfengine.com/job/pr-pipeline/10669/)

**Comment by larsewi** [comment]
[Build Status](https://ci.cfengine.com/job/pr-pipeline/10720/)

**Comment by larsewi** [comment]
I will open this again in the future

**Pull request closed without merging**
