### PR TITLE
Update postgresql to 12beta2

### PR DESCRIPTION
**Pull request by Lex-2008**

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom build it in Jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2325/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2325/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2325/

**Comment by vpodzime** [comment]
@cf-bottom build it in Jenkins again, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2334/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2334/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2334/

**Comment by vpodzime** [comment]
Another try in Jenkins :crossed_fingers: 
[Build Status](https://ci.cfengine.com/job/pr-pipeline)

**Comment by vpodzime** [comment]
> Another try in Jenkins crossed_fingers
And one more... :crossed_fingers: 
[Build Status](https://ci.cfengine.com/job/pr-pipeline/2358/)

**Pull request merged**
