### PR TITLE
postgresql-unhub PR

### PR DESCRIPTION
**Pull request by Lex-2008**
merge together:
https://github.com/cfengine/nova/pull/1466

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom build it

**Comment by Lex-2008** [comment]
@cf-bottom build please

**Comment by Lex-2008** [comment]
build: https://ci.cfengine.com/job/pr-pipeline/2348/

**Comment by Lex-2008** [comment]
rebuild: https://ci.cfengine.com/job/pr-pipeline/2350/

**Comment by Lex-2008** [comment]
build: https://ci.cfengine.com/job/pr-pipeline/2356/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2367/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2367/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2367/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2368/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2368/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2368/

**Comment by Lex-2008** [comment]
build looks good!

**Pull request merged**
