### PR TITLE
Updated git from 2.46.2 to 2.47.0

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/11244/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/11244/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-11244/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/11248/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/11248/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-11248/

**Comment by craigcomstock** [comment]
only known issues, ready for review.

**Review by larsewi — APPROVED** [review]

**Pull request merged**
