### PR TITLE
Enable HTTP/2.0 protocol in apache

### PR DESCRIPTION
**Pull request by aleksandrychev**
Allow using http/2.0 protocol which is significantly better then http/1.1

### CODE REVIEW

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2327/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2327/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2327/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2328/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2328/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2328/

**Pull request closed without merging**
