### PR TITLE
Dependency updates for 3.21.x

### PR DESCRIPTION
**Pull request by Lex-2008**
Updated lmdb from 0.9.29 to 0.9.30
Updated openssl from 3.0.7 to 3.0.8
Updated diffutils from 3.8 to 3.9
Updated openldap from 2.6.3 to 2.6.4
Updated libcurl-hub from 7.86.0 to 7.87.0
Updated apr from 1.7.0 to 1.7.2
Updated apr-util from 1.6.1 to 1.6.3
Updated apache from 2.4.54 to 2.4.55
Updated git from 2.38.1 to 2.39.1
Updated libcurl from 7.86.0 to 7.87.0

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom test plz

**Comment by cf-bottom** [comment]
I'm not sure I understand, @Lex-2008.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9232/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9232/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9232/

**Review by craigcomstock — APPROVED** [review]

**Comment by Lex-2008** [comment]
Green CI: https://ci.cfengine.com/job/pr-pipeline/9253/
and windows build tested manually (on Win7 32-bit) that `diff.exe`, `diff3.exe`, `cmp.exe` and `sdiff.exe` all work and produce expected output.

**Pull request merged**
