### PR TITLE
Upgrade PHP to 7.4.1

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom I wish you could start a jenkins build from here, right? (or do you already?)

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4347/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4347/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4347/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins again, forgot to update version in .spec file.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4348/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4348/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4348/

**Comment by craigcomstock** [comment]
PHP 7.4.2 is released as a security and bugfix release: https://www.php.net/archive/2020.php#2020-01-23-1 so will close this. We can upgrade to latest during next release cycle.

**Pull request closed without merging**
