### PR TITLE
ENT-5431: Added /var/cfengine/lib to install files for libyaml

### PR DESCRIPTION
**Pull request by craigcomstock**
Ticket: ENT-5431
Changelog: title

### CODE REVIEW

**Comment by craigcomstock** [comment]
getting some packages:
https://ci.cfengine.com/job/pr-pipeline/4878/

**Comment by craigcomstock** [comment]
another try: https://ci.cfengine.com/job/pr-pipeline/4879/ (debian only builds)

**Comment by craigcomstock** [comment]
@cf-bottom jenkins full build, thanks.

**Comment by craigcomstock** [comment]
Tested debian8 agent build and it seems fixed. I think this is ready to commit. Unless we want to cherry-pick changes instead of just fixing it like I have done here. Look at ENT-5431 for notes on other related commits.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4880/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4880/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4880/

**Pull request merged**
