### PR TITLE
[3.12.x] RHEL 8

### PR DESCRIPTION
**Pull request by vpodzime**
Merge together:
https://github.com/cfengine/buildscripts/pull/632
https://github.com/cfengine/core/pull/3913
https://github.com/cfengine/enterprise/pull/558
https://github.com/cfengine/nova/pull/1539
https://github.com/cfengine/masterfiles/pull/1639

### CODE REVIEW

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4007/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4007/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4007/

**Comment by vpodzime** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4354/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4354/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4354/

**Comment by vpodzime** [comment]
@cf-bottom another jenkins, please, this time with https://github.com/cfengine/masterfiles/pull/1639 too

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4356/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4356/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4356/

**Pull request merged**
