### PR TITLE
ENT-5255: Made Mission Portal application log relocation more resilient (3.15.x)

### PR DESCRIPTION
**Pull request by craigcomstock**
merge together
https://github.com/cfengine/buildscripts/pull/663
https://github.com/cfengine/mission-portal/pull/995
https://github.com/cfengine/masterfiles/pull/1657

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins check please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4405/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4405/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4405/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins check please, this time with related PRs included

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4408/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4408/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4408/

**Pull request merged**
