### PR TITLE
3.6.x cherry-picks

### PR DESCRIPTION
**Pull request by jimis**
Supersedes https://github.com/cfengine/buildscripts/pull/110.

### CODE REVIEW

**Comment by jimis** [comment]
@kacf I just removed two lines that seemed forgotten and it builds fine. Do you think anything else is forgotten from commit 52f35b9cf719e2b5fa07f11ff185b77d4e9a7d20 ?

**Comment by jimis** [comment]
wow something is wrong here, too many commits.

**Comment by jimis** [comment]
all green

**Comment by kacf** [comment]
Looks good, the `etc` fix looks right to me.

I started a build including all platforms at http://jenkins.usdc.cfengine.com/job/testing-kristian-privateBranch/134/, so maybe it'll be done by the time you start.

**Pull request merged**
