### PR TITLE
ENT-4353 postgresql migration 3.12.x

### PR DESCRIPTION
**Pull request by Lex-2008**

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom build, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2050/)

https://ci.cfengine.com/job/pr-pipeline/2050/

**Comment by vpodzime** [comment]
I've restarted the deployment tests job on this:
[Build Status](https://ci.cfengine.com/job/testing-run-deployment-tests/2351/)

**Comment by Lex-2008** [comment]
it's good, but not enough.
@cf-bottom build, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2060/)

https://ci.cfengine.com/job/pr-pipeline/2060/

**Pull request merged**
