### PR TITLE
CFE-4010: Revert "Workaround automake version problems between bootstrap host a… (3.18)

### PR DESCRIPTION
**Pull request by craigcomstock**
…nd ubuntu 22 build host"

This reverts commit b16e4ee99bf7e5e10258d8a3b0a8c986855fdefe.

(cherry picked from commit 454dbdb3d0198a0a49c11a2d03d13881c4a6df86)

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8537/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8537/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8537/

**Comment by craigcomstock** [comment]
> Alright, I triggered a build:
> 
> [Build Status](https://ci.cfengine.com//job/pr-pipeline/8537/)
> 
> **Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8537/
> 
> **Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8537/


This build had a bunch of odd connectivity problems in AWS build hosts. https://tracker.mender.io/browse/ENT-9123

**Comment by craigcomstock** [comment]
@cf-bottom jenkins again, see if AWS build hosts fare better.

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8539/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8539/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8539/

**Comment by craigcomstock** [comment]
merged this without a full green CI run, most hosts worked, DTs didn't execute maybe due to jenkins OOM problem. This is really a revert anyway so ok to merge without full green. Known issues are being worked with regard to arm64 failures.

**Pull request merged**
