### PR TITLE
ENT-3525: remove pgtap dep for travis

### PR DESCRIPTION
**Pull request by craigcomstock**
merge with  https://github.com/cfengine/nova/pull/1224

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a pull request! Maybe @Lex-2008 can review this?

**Comment by olehermanse** [comment]
@craigcomstock looks like this one will need a rebase now.

**Comment by craigcomstock** [comment]
@olehermanse right you are. done.

**Comment by olehermanse** [comment]
@Lex-2008 @craigcomstock I hate merging things in buildscripts and not knowing whether it will break core CI, but here goes!

**Pull request merged**
