### PR TITLE
ENT-4904 no git commands run in postinst script

### PR DESCRIPTION
**Pull request by Lex-2008**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a pull request! Maybe @craigcomstock can review this?

**Comment by Lex-2008** [comment]
@cf-bottom build it please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2660/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2660/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2660/

**Comment by Lex-2008** [comment]
PR to fix the broken deployment test: https://github.com/cfengine/system-testing/pull/241

**Comment by Lex-2008** [comment]
yup, already tested with the above build, using VCS deployment with SSH key.

**Pull request merged**
