### PR TITLE
Redmine #7605: Fix Solaris postinstall script hanging.

### PR DESCRIPTION
**Pull request by pasinskim**

### CODE REVIEW

**Comment by pasinskim** [comment]
trigger build

**Comment by pasinskim** [comment]
@kacfengine the build is green and I have installed package on Solaris to test it. Installation was fine and SIGILL signal we've seen before that might cause problems is not even emitted right now.

**Comment by kacfengine** [comment]
Let's see what the reporter says before we merge this.

**Comment by pasinskim** [comment]
@kacfengine as we have code freeze today and this is not breaking anything maybe this will be safe to merge anyway?

**Comment by kacfengine** [comment]
Yep!

**Comment by kacfengine** [comment]
Cherry-picked to 3.7.x and 3.8.x as well.

**Pull request merged**
