### PR TITLE
Dependency updates for 3.12.x

### PR DESCRIPTION
**Pull request by Lex-2008**
Update pcre from 8.43 to 8.44
Update openldap from 2.4.48 to 2.4.49
Update libcurl-hub from 7.67.0 to 7.69.0
Update git from 2.24.0 to 2.25.1
Update postgresql from 10.11 to 10.12
Update php from 7.2.24 to 7.2.28
Update libcurl from 7.67.0 to 7.69.0

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom build it now

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4796/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4796/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4796/

**Comment by Lex-2008** [comment]
@cf-bottom add exotics to jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4803/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4803/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4803/

**Pull request merged**
