### PR TITLE
Dependency updates for 3.12.x

### PR DESCRIPTION
**Pull request by Lex-2008**
Update libyaml from 0.1.7 to 0.2.1
Update libcurl-hub from 7.59.0 to 7.62.0
Update apr from 1.6.3 to 1.6.5
Update apache from 2.4.33 to 2.4.35
Update git from 2.17.1 to 2.19.1
Update php from 7.2.6 to 7.2.12
Update libcurl from 7.60.0 to 7.62.0

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a PR! Maybe @craigcomstock can review this?

**Comment by Lex-2008** [comment]
some deps didn't update automagically, must do it manually first

**Comment by Lex-2008** [comment]
@cf-bottom build, please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1673/)

https://ci.cfengine.com/job/pr-pipeline/1673/

**Comment by Lex-2008** [comment]
thank you!

**Comment by Lex-2008** [comment]
@cf-bottom build this without exotics, please!

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/1676/)

(with exotics)

https://ci.cfengine.com/job/pr-pipeline/1676/

**Comment by Lex-2008** [comment]
_exactly_ what I asked 4!

**Comment by Lex-2008** [comment]
Build is rather green in Jenkins. @vpodzime: do you see any issues or is it OK to merge?

**Pull request merged**
