### PR TITLE
Update libxml2 and use xz package

### PR DESCRIPTION
**Pull request by Lex-2008**
Ticket: ENT-9539

### CODE REVIEW

**Comment by Lex-2008** [comment]
testbuild1: https://ci.cfengine.com/job/pr-pipeline/8809/ - does it build? at all?

**Comment by Lex-2008** [comment]
@cf-bottom build exotics plz

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8825/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8825/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8825/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8827/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8827/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8827/

**Pull request merged**
