### PR TITLE
INF-1253 Add explicit build numbers

### PR DESCRIPTION
**Pull request by Lex-2008**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thanks for submitting a pull request! Maybe @craigcomstock can review this?

**Comment by Lex-2008** [comment]
I'd like this to be merged before 3.15.0

**Comment by Lex-2008** [comment]
testbuild: https://ci.cfengine.com/job/pr-pipeline/4319/

**Comment by Lex-2008** [comment]
hpux build failed because:
```
12:54:21 ssh: connect to host cloud.siteox.com port 35622: No route to host
```

**Comment by Lex-2008** [comment]
build with all packages except hpux green: https://ci.cfengine.com/job/pr-pipeline/4321/
build with only hpux package: https://ci.cfengine.com/job/pr-pipeline/4322/

**Comment by Lex-2008** [comment]
green && approved && merged

**Pull request merged**
