### PR TITLE
ENT-4515 rotate keys 3.10.x

### PR DESCRIPTION
**Pull request by Lex-2008**

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom build

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2406/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2406/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2406/

**Comment by Lex-2008** [comment]
@cf-bottom bad build

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2407/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2407/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2407/

**Pull request merged**
