### PR TITLE
Added libexpat as explicit dependency

### PR DESCRIPTION
**Pull request by Lex-2008**
Ticket: ENT-9105

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom build it

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8544/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8544/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8544/

**Comment by Lex-2008** [comment]
Jenkins failures seem unrelated. Any objections to merge?

**Review by vpodzime — COMMENTED** [review]
Please be more elaborate in the commit message, especially regarding:
- why we need this
- why we don't bundle this

**Comment by craigcomstock** [comment]
> Please be more elaborate in the commit message, especially regarding:
> 
> * why we need this
> * why we don't bundle this

Yeah. Second that for sure. We don't want to add too many of these else we loose the benefit of bundling things.

**Comment by Lex-2008** [comment]
commit message expanded! Also found where it regressed.

**Review by craigcomstock — APPROVED** [review]

**Review by vpodzime — APPROVED** [review]
ACK. Fortunately `dnf repoquery --whatrequires expat` shows that `expat` is very commonly used and thus required by many core things (incl. `python3`, for example).

**Pull request merged**
