### PR TITLE
3.14.0-x PR

### PR DESCRIPTION
**Pull request by Lex-2008**
very much like https://github.com/cfengine/buildscripts/pull/583, but for different PostgreSQL version

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a pull request! Maybe @craigcomstock can review this?

**Comment by Lex-2008** [comment]
testbuild: https://ci.cfengine.com/job/pr-pipeline/2410/

**Comment by craigcomstock** [comment]
Is there some sort of fingerprint from postgresql for this CVE patch? Just wondering.

**Comment by Lex-2008** [comment]
what do you mean under "fingerprint"? A way to test it?

**Pull request merged**
