### PR TITLE
Dependency updates for 3.15.x

### PR DESCRIPTION
**Pull request by Lex-2008**
Update zlib from 1.2.11 to 1.2.12
~Update openssl from 1.1.1l to 3.0.3~
~Update libiconv from 1.16 to 1.17~
Update libcurl-hub from 7.79.1 to 7.83.1
Update git from 2.33.1 to 2.36.1
Update rsync from 3.2.3 to 3.2.4
Update postgresql from 12.8 to 12.11
Update php from 7.4.25 to 7.4.29
Update libcurl from 7.79.1 to 7.83.1
Update apache from 2.4.51 to 2.4.53

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a PR! Maybe @craigcomstock can review this?

**Comment by Lex-2008** [comment]
@cf-bottom: did you build it first?

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8000/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8000/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8000/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8026/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8026/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8026/

**Pull request merged**
