### PR TITLE
ENT-9621: Added support for redhat 9 agent (3.18)

### PR DESCRIPTION
**Pull request by craigcomstock**
Ticket: ENT-9621
Changelog: title

merge together:
https://github.com/cfengine/buildscripts/pull/1159
https://github.com/cfengine/core/pull/5114
https://github.com/cfengine/masterfiles/pull/2544

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please, thanks

**Comment by craigcomstock** [comment]
trying a redhat 9 with no tests build first: [Build Status](https://ci.cfengine.com/job/pr-pipeline/8940/)

I might tell cf bot tom something like "build no tests label like redhat_9" maybe? ;)

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by craigcomstock** [comment]
try again, I had added to much in selinux policy related to cf-reactor cfbs integration which is not present in 3.18.x.

[Build Status](https://ci.cfengine.com/job/pr-pipeline/8946/)

**Comment by craigcomstock** [comment]
Forgot to include the patch in core which loads the default and legacy providers, so was breaking core/tests/unit/crypto_symmetric_test.

retry with only redhat9:
[Build Status](https://ci.cfengine.com/job/pr-pipeline/8957/)

**Comment by craigcomstock** [comment]
@cf-bottom jenkins for all platforms now that redhat9 alone passes.

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8959/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8959/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8959/

**Comment by craigcomstock** [comment]
@vpodzime @Lex-2008 failures of last CI run are either lmdb issues (seen as apt_get wrapper problem) or ssh connection problems. So I think this set of PRs is "good to go".

**Review by vpodzime — APPROVED** [review]
ACK

**Review by Lex-2008 — APPROVED** [review]

**Pull request merged**
