### PR TITLE
added debian11 to the mix

### PR DESCRIPTION
**Pull request by Lex-2008**

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom will it build?

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7321/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7321/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7321/

**Comment by craigcomstock** [comment]
Adjusted debian11 setup config in jenkins to install python2 and python-psycopg2. Retry: [Build Status](https://ci.cfengine.com/job/pr-pipeline/7330/)

**Comment by craigcomstock** [comment]
> Adjusted debian11 setup config in jenkins to install python2 and python-psycopg2. Retry: [Build Status](https://ci.cfengine.com/job/pr-pipeline/7330/)

cancelled, need debian 11 hub

**Comment by craigcomstock** [comment]
debian 11 retry now that we have both HUB and non-HUB [Build Status](https://ci.cfengine.com/job/pr-pipeline/7331/)

**Comment by craigcomstock** [comment]
@Lex-2008 looks like we might need more config things in jenkins from ubuntu20? I'm not sure.

maybe failure for debian 11 HUB was:
```
10:02:32 Test Summary Report
10:02:32 -------------------
10:02:32 corrupt.test           (Wstat: 0 Tests: 0 Failed: 0)
10:02:32   Parse errors: No plan found in TAP output
10:02:32 empty.test             (Wstat: 0 Tests: 0 Failed: 0)
10:02:32   Parse errors: No plan found in TAP output
10:02:32 empty_variable.test    (Wstat: 0 Tests: 0 Failed: 0)
10:02:32   Parse errors: No plan found in TAP output
10:02:32 failed_delta.test      (Wstat: 0 Tests: 0 Failed: 0)
10:02:32   Parse errors: No plan found in TAP output
10:02:32 multihost_reports.test (Wstat: 0 Tests: 0 Failed: 0)
10:02:32   Parse errors: No plan found in TAP output
10:02:32 rebase.test            (Wstat: 0 Tests: 0 Failed: 0)
10:02:32   Parse errors: No plan found in TAP output
10:02:32 rebase_delta_delta.test (Wstat: 0 Tests: 0 Failed: 0)
10:02:32   Parse errors: No plan found in TAP output
10:02:32 Files=7, Tests=0, 79 wallclock secs ( 0.18 usr  0.02 sys +  6.63 cusr  3.88 csys = 10.71 CPU)
10:02:32 Result: FAIL
```

**Comment by craigcomstock** [comment]
Nope. It was this:

```
10:01:17 Traceback (most recent call last):
10:01:26   File "corrupt_test.py", line 5, in <module>
10:01:26     from reporting_test import ReportData, ReportSpec, ReportTest, CFTestdManager, SQLAssert, TempFile
10:01:26   File "/home/jenkins/workspace/testing-pr/label/PACKAGES_HUB_x86_64_linux_debian_11/nova/tests/reporting/reporting_test.py", line 2, in <module>
10:01:26     import psycopg2
10:01:26 ImportError: No module named psycopg2
```

So I will double-check that.

**Comment by craigcomstock** [comment]
I see the problem. I added the psycopg2 stuff in the instance and not the cloud configs. Fixing now and will rebuild.

**Comment by craigcomstock** [comment]
test failures are expected given the filter on hosts built in last build. Basic stuff is ok-to-go so will run through a proper jenkins run now :)

@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7337/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7337/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7337/

**Comment by Lex-2008** [comment]
canary is dead in the above build, retrying for debian 10/11 only: https://ci.cfengine.com/job/pr-pipeline/7339/

**Comment by craigcomstock** [comment]
With https://github.com/cfengine/buildscripts/pull/895 merged let's try a fresh full CI build.

@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7342/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7342/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7342/

**Pull request merged**
