### PR TITLE
ENT-9037: Added cf-support binary to packages 

### PR DESCRIPTION
**Pull request by craigcomstock**
Ticket: ENT-9037
Changelog: title

merge together:
https://github.com/cfengine/core/pull/5010
https://github.com/cfengine/nova/pull/1918
https://github.com/cfengine/buildscripts/pull/1106
https://github.com/cfengine/system-testing/pull/445

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please no tests (I'll run tests later on the packages generated)

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8400/)

 [NO TESTS]

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8400/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8400/

**Comment by craigcomstock** [comment]
Let's try that build again, no tests, exotics this time. deb and rpm packages should be good. scripts should be pretty good as well. 

[Build Status](https://ci.cfengine.com/job/pr-pipeline/8415/)

**Comment by craigcomstock** [comment]
Try again with core using `dist_bin_SCRIPTS` instead of `bin_SCRIPTS` to avoid automake wanting to "build" `cf-support` script. 

@cf-bottom jenkins no tests

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8451/)

 [NO TESTS]

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8451/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8451/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins again, no tests

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8452/)

 [NO TESTS]

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8452/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8452/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8456/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8456/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8456/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8457/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8457/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8457/

**Comment by craigcomstock** [comment]
can't quite get tom to build this for me, so did it myself:

https://ci.cfengine.com/job/pr-pipeline/8459/

[Build Status](https://ci.cfengine.com/job/pr-pipeline/8459/)

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8460/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8460/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8460/

**Review by Lex-2008 — APPROVED** [review]

**Comment by vpodzime** [comment]
Please squash the commits.

**Comment by craigcomstock** [comment]
> Please squash the commits.

Done. Thanks :+1:

**Pull request merged**
