### PR TITLE
Minor dependency updates (3.21)

### PR DESCRIPTION
**Pull request by craigcomstock**
with https://github.com/cfengine/system-testing/pull/579

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/11333/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/11333/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-11333/

**Comment by craigcomstock** [comment]
issues are either flaky or supposedly already resolved
- ENT-11526, application logs change permissions which should be resolved
- [ENT-9764](https://northerntech.atlassian.net/browse/ENT-9764) flake found with regex ssh_exchange_identification
- [ENT-11189](https://northerntech.atlassian.net/browse/ENT-11189) flake found with regex Method.*mission_portal_apache_from_stage.*failed in some repairs

**Review by larsewi — APPROVED** [review]

**Comment by craigcomstock** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/11358/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/11358/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-11358/

**Comment by craigcomstock** [comment]
green enough

**Pull request merged**
