### PR TITLE
ENT-10897: master deps 2023 11 13 14 33 15 538340

### PR DESCRIPTION
**Pull request by craigcomstock**
- Updated lmdb from 0.9.30 to 0.9.31
- Updated zlib from 1.2.13 to 1.3
- Updated openssl from 3.1.1 to 3.1.4
- Updated libxml2 from 2.11.4 to 2.11.5
- Updated openldap from 2.6.4 to 2.6.6
- Updated libcurl-hub from 8.1.2 to 8.4.0
- Updated apache from 2.4.57 to 2.4.58
- Updated git from 2.41.0 to 2.42.1
- Updated postgresql from 15.3 to 15.5
- Updated php from 8.2.7 to 8.2.12
- Updated libcurl from 8.1.2 to 8.4.0

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10040/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10040/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10040/

**Comment by craigcomstock** [comment]
rhel8 testing-pr targets aborted due to AWS problem which is now fix, will re-run.

[Build Status](https://ci.cfengine.com/job/pr-pipeline/10049/)

**Comment by craigcomstock** [comment]
looks like libcurl failed on hpux 11.23

```
10:44:05   CC       libcurl_la-file.lo
10:44:07   CC       libcurl_la-fileinfo.lo
10:44:09   CC       libcurl_la-fopen.lo
10:44:10   CC       libcurl_la-formdata.lo
10:44:12 formdata.c: In function 'fseeko_wrapper':
10:44:13 formdata.c:796: error: implicit declaration of function 'fseeko'
10:44:13 Makefile:2472: recipe for target 'libcurl_la-formdata.lo' failed
10:44:13 gmake[2]: *** [libcurl_la-formdata.lo] Error 1
10:44:13 gmake[2]: Leaving directory '/home/jenkins/workspace/testing-pr/label/PACKAGES_ia64_hpux_11.23/libcurl/pkg/lib'
10:44:13 Makefile:1503: recipe for target 'all' failed
10:44:13 gmake[1]: Leaving directory '/home/jenkins/workspace/testing-pr/label/PACKAGES_ia64_hpux_11.23/libcurl/pkg/lib'
10:44:13 Makefile:1273: recipe for target 'all-recursive' failed
```

will investigate and try to fix.

**Comment by craigcomstock** [comment]
retry hpux [Build Status](https://ci.cfengine.com/job/pr-pipeline/10053/)

**Comment by craigcomstock** [comment]
closing this, I can't push here due to branch protection and this branch matches `master`

**Comment by craigcomstock** [comment]
https://github.com/cfengine/buildscripts/pull/1342

**Pull request closed without merging**
