### PR TITLE
Dependency updates for master

### PR DESCRIPTION
**Pull request by Lex-2008**
Updated openssl from 3.1.0 to 3.1.1
Updated libxml2 from 2.11.1 to 2.11.4
Updated diffutils from 3.9 to 3.10
Updated libcurl-hub from 8.0.1 to 8.1.2
Updated git from 2.40.1 to 2.41.0
Updated postgresql from 15.2 to 15.3
Updated php from 8.2.5 to 8.2.7
Updated libcurl from 8.0.1 to 8.1.2

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom build exotics, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/9539/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/9539/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-9539/

**Comment by Lex-2008** [comment]
build is green enough, ready to be reviewed!

**Review by nickanderson — APPROVED** [review]
Looks ok to me.

**Pull request merged**
