### PR TITLE
Dependency updates for 3.12.x

### PR DESCRIPTION
**Pull request by Lex-2008**
Update libyaml from 0.2.4 to 0.2.5
Update openldap from 2.4.50 to 2.4.53
Update libcurl-hub from 7.70.0 to 7.72.0
Update apache from 2.4.43 to 2.4.46
Update git from 2.26.2 to 2.28.0
Update postgresql from 10.12 to 10.14
Update php from 7.2.30 to 7.2.34
Update libcurl from 7.70.0 to 7.72.0

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom build exotics please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5706/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5706/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5706/

**Comment by Lex-2008** [comment]
@cf-bottom build with exotics

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5881/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5881/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5881/

**Pull request merged**
