### PR TITLE
ENT-5430 Fix userworkdir permissions - 3.12.x

### PR DESCRIPTION
**Pull request by Lex-2008**

### CODE REVIEW

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4881/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4881/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4881/

**Comment by aleksandrychev** [comment]
@Lex-2008 the previous error is gone, now I see different one 
`Error setting up new clone repository for staging area. sh: 1: /var/cfengine/httpd/htdocs/api/dc-scripts/git-wrapper.sh: Permission denied`

**Comment by Lex-2008** [comment]
Hmm, so maybe I deleted too much back then...

**Comment by Lex-2008** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4882/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4882/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4882/

**Pull request merged**
