### PR TITLE
Dependency updates for 3.12.x

### PR DESCRIPTION
**Pull request by Lex-2008**
Update lmdb from 0.9.23 to 0.9.24
Update openssl from 1.1.1b to 1.1.1d
Update sasl2 from 2.1.26 to 2.1.27
Update libiconv from 1.15 to 1.16
Update libxml2 from 2.9.9 to 2.9.10
Update openldap from 2.4.47 to 2.4.48
Update libcurl-hub from 7.64.1 to 7.66.0
Update apache from 2.4.39 to 2.4.41
Update postgresql from 10.7 to 10.10
Update php from 7.2.18 to 7.2.24
Update libcurl from 7.64.1 to 7.66.0

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom build, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4048/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4048/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4048/

**Comment by Lex-2008** [comment]
ready to be reviewed!
@cf-bottom: will the build on exotics turn out green?

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4122/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4122/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4122/

**Comment by Lex-2008** [comment]
The build is green enough:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4135/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4135/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4135/

OK to review!

**Comment by Lex-2008** [comment]
note to self: writing "ready to be reviewed" doesn't help, if nobody is assigned

**Pull request merged**
