### PR TITLE
WIP: Added http2 support to Apache

### PR DESCRIPTION
**Pull request by aleksandrychev**
ChangeLog: None

### CODE REVIEW

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4652/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4652/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4652/

**Comment by Lex-2008** [comment]
added new dependency, retriggered the build: https://ci.cfengine.com/job/pr-pipeline/4653/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by aleksandrychev** [comment]
@Lex-2008 thank you!

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4661/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4661/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4661/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4663/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4663/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4663/

**Pull request closed without merging**
