### PR TITLE
ENT-8822 Document CI Workflow

### PR DESCRIPTION
**Pull request by craigcomstock**

### CODE REVIEW

**Comment by craigcomstock** [comment]
yeah yeah yeah, I see you github, you don't support include in asciidoc or org mode so I have to hack in order to "get what I want": literate docs that include code which is executed in CI! a todo to figure out how to slice this :)

**Review by Lex-2008 — APPROVED** [review]
nice!

**Comment by craigcomstock** [comment]
These basic instructions work fine in a container :) Takes about 12-14 minutes running in an ubuntu virtualbox (4cpu) on my macos macbook pro (4cpu) :) So the container has "all four" cpu as well.

```
++ ls -l cfengine-community/cfengine-community_3.21.0a.6ed7e4f38~.debian11_amd64.deb
-rw-r--r-- 1 root root 5083232 Jul 21 18:47 cfengine-community/cfengine-community_3.21.0a.6ed7e4f38~.debian11_amd64.deb
root@ddb6d158721e:~/cfengine# cat /etc/issue
Debian GNU/Linux 11 \n \l
```

**Review by vpodzime — APPROVED** [review]
ACK

**Pull request merged**
