### PR TITLE
Dependency updates for master

### PR DESCRIPTION
**Pull request by Lex-2008**
Update zlib from 1.2.11 to 1.2.12
Update libcurl-hub from 7.80.0 to 7.83.0
Update git from 2.34.1 to 2.36.0
Update rsync from 3.2.3 to 3.2.4
Update libcurl from 7.80.0 to 7.83.0
Update openldap from 2.6.0 to 2.6.1
Update apache from 2.4.51 to 2.4.53
Update php from 8.0.12 to 8.0.19

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom build exotics

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7892/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7892/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7892/

**Comment by Lex-2008** [comment]
@cf-bottom build

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7935/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7935/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7935/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7945/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7945/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7945/

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/7952/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/7952/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-7952/

**Pull request merged**
