### PR TITLE
Drop CFE from package name

### PR DESCRIPTION
**Pull request by Lex-2008**
Ticket: ENT-8938

### CODE REVIEW

**Comment by Lex-2008** [comment]
testbuild: https://ci.cfengine.com/job/pr-pipeline/8272/

**Review by vpodzime — APPROVED** [review]
Looks good to me.

**Comment by Lex-2008** [comment]
@cf-bottom now that exotics are ready, you can build this

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8513/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8513/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8513/

**Review by vpodzime — COMMENTED** [review]
The commit message should mention Solaris. Looks good to me otherwise.

**Comment by Lex-2008** [comment]
solaris + linux testbuild (to check deploytests): https://ci.cfengine.com/job/pr-pipeline/8549/

**Review by vpodzime — CHANGES_REQUESTED** [review]
Still think the commit should mention Solaris.

**Comment by Lex-2008** [comment]
closing in favour of https://github.com/cfengine/buildscripts/pull/1120

**Pull request closed without merging**
