### PR TITLE
Upgraded cfbs to version 4.1.0 (3.21)

### PR DESCRIPTION
**Pull request by olehermanse**

### CODE REVIEW

**Comment by olehermanse** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/10895/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/10895/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-10895/

**Comment by vpodzime** [comment]
Too late :stuck_out_tongue:

**Comment by larsewi** [comment]
The failure in bootstrap test
```
expected 1 cf-hub processes running but found 2
```
looks like it's related to https://github.com/cfengine/system-testing/pull/554 🤔

**Review by larsewi — APPROVED** [review]

**Comment by vpodzime** [comment]
and
```
34.245.141.76	curl: (22) The requested URL returned error: 422 Unprocessable Entity
```
which hits the fact that 3.21.4 is the latest release of the masterfiles module and it has the non-patched policy for httpd.conf and httpd restart.

**Pull request merged**
