### PR TITLE
Update agent dependencies.

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by jimis** [comment]
trigger build

**Comment by kacfengine** [comment]
What can go wrong? :-)

**Comment by kacfengine** [comment]
+1

**Comment by jimis** [comment]
@kacfengine you should see the next push I'll do after this succeeds, completely deleting some forgotten dependencies to really see what can go wrong. :-)

**Comment by jimis** [comment]
Heh, windows is already dead, ehm, red.

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
trigger build

**Comment by jimis** [comment]
I squashed all fixes in relevant commits since the build seems to be going for green. Unfortunately I had to completely drop the commits that updated OpenSSL since I couldn't make MinGW cooperate.

Nevertheless I'm merging in an effort to honour the deadline. @kacfengine feel free to branch-off in the morning.

**Pull request merged**
