### PR TITLE
ENT-5329 use ibm cecc aix

### PR DESCRIPTION
**Pull request by Lex-2008**

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a pull request! Maybe @craigcomstock can review this?

**Comment by craigcomstock** [comment]
This is a WIP right? (_test, commented out things) Maybe mark it as such.

**Comment by Lex-2008** [comment]
indeed, thanks!

**Comment by vpodzime** [comment]
Added a commit here that is also part of #731. I think we should merge that PR and then drop it from here.

**Comment by Lex-2008** [comment]
new rebuild: https://ci.cfengine.com/job/pr-pipeline/5010/

**Comment by Lex-2008** [comment]
Merging this while none sees, so nightlies could work on the new AIX.

**Pull request merged**
