### PR TITLE
ENT-5255: Made Mission Portal application log relocation more resilient (3.12.x)

### PR DESCRIPTION
**Pull request by craigcomstock**
merge together
https://github.com/cfengine/buildscripts/pull/662
https://github.com/cfengine/masterfiles/pull/1656
https://github.com/cfengine/mission-portal/pull/994

### CODE REVIEW

**Comment by craigcomstock** [comment]
@cf-bottom jenkins check please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4406/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4406/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4406/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins again, with related PRs included

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/4409/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/4409/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-4409/

**Pull request merged**
