### PR TITLE
ENT-10997: Added Debian 12 labels to buildscripts (3.18.x)

### PR DESCRIPTION
**Pull request by larsewi**
Merge together:
* https://github.com/cfengine/core/pull/5411

### CODE REVIEW

**Comment by larsewi** [comment]
@cf-bottom Jenkins please :)

**Comment by larsewi** [comment]
[Build Status](https://ci.cfengine.com/job/pr-pipeline/10227/)

**Review by craigcomstock — APPROVED** [review]

**Comment by larsewi** [comment]
[Build Status](https://ci.cfengine.com/job/pr-pipeline/10238/)

**Comment by larsewi** [comment]
[Build Status](https://ci.cfengine.com/job/pr-pipeline/10240/)

**Comment by craigcomstock** [comment]
@larsewi remember that as a member of the cfengine organization you can push to upstream to get all CI going.

```
Secret GH_ACTIONS_SSH_DEPLOY_KEY_ENTERPRISE_REPO is required, but not provided while calling.
```

https://github.com/cfengine/buildscripts/actions/runs/7341219877?pr=1356

https://northerntech.atlassian.net/browse/ENT-11097 has some nice related tickets which will bring some amount of CI to PRs from forks.

**Pull request merged**
