### PR TITLE
php8 Dependency update for master

### PR DESCRIPTION
**Pull request by Lex-2008**
Update php from 7.4.12 to 8.0.2

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom build it exotics please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6111/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6111/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6111/

**Comment by Lex-2008** [comment]
update: https://ci.cfengine.com/job/pr-pipeline/6113/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins please (will canaries pass with the nova changes?)

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6119/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6119/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6119/

**Comment by craigcomstock** [comment]
Oops. Forgot the .h files :p, Try again. @cf-bottom jenkins please :)

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6120/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6120/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6120/

**Comment by craigcomstock** [comment]
@Lex-2008 it seems two issues in failures: virtual memory exhausted, and mysterious (as in debian 7 build). I'll leave you to work on this for a bit. Ping me if you think I can help.

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6233/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6233/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6233/

**Comment by Lex-2008** [comment]
above jenkins build lacks mission-portal PR. @cf-bottom?

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6235/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6235/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6235/

**Comment by Lex-2008** [comment]
that's better! Thank you, @cf-bottom.

**Comment by cf-bottom** [comment]
I'm not sure I understand, @Lex-2008.

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6265/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6265/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6265/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6267/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6267/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6267/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6306/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6306/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6306/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6307/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6307/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6307/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6308/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6308/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6308/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6316/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6316/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6316/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6332/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6332/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6332/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6346/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6346/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6346/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6347/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6347/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6347/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6348/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6348/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6348/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6350/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6350/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6350/

**Comment by aleksandrychev** [comment]
@Lex-2008 build is finally green

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6372/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6372/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6372/

**Review by aleksandrychev — APPROVED** [review]

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6379/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6379/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6379/

**Comment by aleksandrychev** [comment]
@cf-bottom jenkins

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/6385/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/6385/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-6385/

**Pull request merged**
