### PR TITLE
Dependency updates for 3.10.x

### PR DESCRIPTION
**Pull request by Lex-2008**
Update lcov from 1.13 to 1.14
Update lmdb from 0.9.22 to 0.9.23
Update pcre from 8.42 to 8.43
~Update sasl2 from 2.1.26 to 2.1.27~
~Update libxml2 from 2.9.8 to 2.9.9~
Update libyaml from 0.2.1 to 0.2.2
Update openldap from 2.4.46 to 2.4.47
Update libcurl-hub from 7.61.1 to 7.64.1
Update apr from 1.6.5 to 1.7.0
Update apache from 2.4.35 to 2.4.39
Update git from 2.13.6 to ~2.21.0~ 2.13.7
Update postgresql-hub from 9.6.10 to 9.6.12
Update php from 5.6.38 to 5.6.40
Update redis from 3.2.12 to 3.2.13
Update libcurl from 7.61.1 to 7.64.1
Update OpenSSL from 1.0.2p to 1.0.2r

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a PR! Maybe @craigcomstock can review this?

**Comment by Lex-2008** [comment]
@cf-bottom does it build?

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/2378/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/2378/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-2378/

**Comment by Lex-2008** [comment]
ready to be reviewed! Not a lot of interesting stuff to look at, however, I suppose

**Comment by olehermanse** [comment]
@Lex-2008 Please note that this did not pass in jenkins(!).

**Pull request merged**
