### PR TITLE
Added ubuntu 20 and 22 support on aarch64 platform (3.18)

### PR DESCRIPTION
**Pull request by craigcomstock**
Ticket: ENT-8623

### CODE REVIEW

**Comment by cf-bottom** [comment]
Thank you for submitting a PR! Maybe @Lex-2008 can review this?

**Review by nickanderson — APPROVED** [review]

**Comment by nickanderson** [comment]
@cf-bottom jenkins, please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8286/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8286/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8286/

**Comment by nickanderson** [comment]
@cf-bottom, how about a jenkins build with exotics?

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8287/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8287/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8287/

**Comment by craigcomstock** [comment]
Ah, probably we need some more changes in masterfiles back-ported to 3.18.x for this to pass. :+1:

**Comment by craigcomstock** [comment]
@nickanderson can you look at this failure? You added the test about a month ago around the time I was putting in ubuntu 20/22 support in master.

https://ci.cfengine.com/job/testing-pr/21275/label=PACKAGES_HUB_arm_64_linux_ubuntu_22/testReport/junit/._31_tickets_ENT-8788_2_main/cf/main_cf/

https://github.com/cfengine/core/blob/master/tests/acceptance/31_tickets/ENT-8788/2/main.cf

**Comment by craigcomstock** [comment]
retrying arm only hosts with the linked core tests fix to disable non-working acceptance tests on ubu20/22 [Build Status](https://ci.cfengine.com/job/pr-pipeline/8292/)

**Comment by nickanderson** [comment]
> @nickanderson can you look at this failure? You added the test about a month ago around the time I was putting in ubuntu 20/22 support in master.
> 
> https://ci.cfengine.com/job/testing-pr/21275/label=PACKAGES_HUB_arm_64_linux_ubuntu_22/testReport/junit/._31_tickets_ENT-8788_2_main/cf/main_cf/
> 
> https://github.com/cfengine/core/blob/master/tests/acceptance/31_tickets/ENT-8788/2/main.cf


I don't see anything in here that is platform specific. After staring at it for 20 minutes nothing jumps out at me.

It only fails on arm64?

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8295/)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8295/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8295/

**Comment by craigcomstock** [comment]
try again @cf-bottom jenkins this time with exotics

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8298/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8298/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8298/

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8306/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8306/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8306/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins exotics again please

**Comment by craigcomstock** [comment]
@cf-bottom build with exotics please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8382/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8382/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8382/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins exotics please

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8387/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8387/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8387/

**Comment by craigcomstock** [comment]
sequential tests failure was an hp/ux build host problem.
arm failures should be related to masterfiles changes to skip certain tests on aarch64 platform.

@cf-bottom lets try jenkins exotics again

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8388/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8388/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8388/

**Comment by craigcomstock** [comment]
@cf-bottom jenkins with exotics

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/8391/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/8391/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-8391/

**Comment by craigcomstock** [comment]
I suspect that the sequential-tests are all errors related to hp/ux test host not behaving well or not being accessible via ssh.

**Pull request merged**
