### PR TITLE
Dependency updates for 3.15.x

### PR DESCRIPTION
**Pull request by Lex-2008**
Update libyaml from 0.2.4 to 0.2.5
Update openldap from 2.4.50 to 2.4.53
Update libcurl-hub from 7.70.0 to 7.72.0
Update apache from 2.4.43 to 2.4.46
Update git from 2.26.2 to 2.28.0
Update postgresql from 12.2 to 13.0
Update php from 7.4.5 to 7.4.10
Update libcurl from 7.70.0 to 7.72.0

### CODE REVIEW

**Comment by Lex-2008** [comment]
@cf-bottom build exotics please

**Comment by cf-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5707/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5707/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5707/

**Comment by Lex-2008** [comment]
new build: https://ci.cfengine.com/job/pr-pipeline/5752/

**Comment by craigcomstock** [comment]
hpux passes: https://ci.cfengine.com/job/pr-pipeline/5826/

I researched solaris 10 x86_64 and it seems to be a segfault problem involving hast_test in libntech and the openssl library.

**Comment by Lex-2008** [comment]
@cf-bottom : build with exotics and :crossed_fingers:

**Comment by cf-bottom** [comment]
Alright, I triggered a build:

[Build Status](https://ci.cfengine.com//job/pr-pipeline/5835/)

(with exotics)

**Jenkins:** https://ci.cfengine.com/job/pr-pipeline/5835/

**Packages:** http://buildcache.cfengine.com/packages/testing-pr/jenkins-pr-pipeline-5835/

**Pull request merged**
